ORG 0100H
.DATA
N DW ?
RESULT DW ?
.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    ;INPUT
    ;FAST BX=0
    XOR BX,BX
INPUT_LOOP:
    ;CHAR INPUT
    MOV AH,1
    INT 21H
    ;IF\N\R,STOP TAKING INPUT
    CMP AL,10
    JE END_INPUT_LOOP
    CMP AL,13
    JE END_INPUT_LOOP
    ;FAST CHAR TO DIGIT
    ;ALSO CLEARS AH
    AND AX,000FH
    ;SAVE AX
    MOV CX,AX
    ;BX=BX*10+AX
    MOV AX,10
    MUL BX
    ADD AX,CX
    MOV BX,AX
    JMP INPUT_LOOP    
END_INPUT_LOOP:
    MOV N,BX
    XOR AX,AX
    ;SHITHING BY 3
    MOV BX,N
    MOV CX,3
    SHR BX,CL 
    ADD AX,BX
    
    MOV RESULT,AX  
    
    MAIN ENDP
END MAIN
RET